[package]
name    = "dwm1001"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-robotics.com>"]


[dependencies]
cortex-m             = { version = "0.5.4", features = [ "const-fn" ] }
cortex-m-rt          = "0.6.3"
cortex-m-semihosting = "0.3.0"
dw1000               = { git = "https://github.com/braun-robotics/rust-dw1000.git" }
embedded-hal         = "0.2.1"
# This is my fork of nrf52-hal. I'm depending on it for the time being, until
# work on it has settled down a bit.
nrf52832-hal         = { git = "https://github.com/braun-robotics/nrf52-hal.git" }

[patch."https://github.com/braun-robotics/nrf52-hal.git"]
nrf52832-hal = { path = "../nrf52-hal/nrf52832-hal" }


[dev-dependencies]
heapless          = "0.3.7"
nb                = "0.1.1"
panic-semihosting = "0.5.0"


[features]
dev         = []                  # expose features of DWM1001-Dev board
rt          = ["nrf52832-hal/rt"]
semihosting = []                  # enable debug output in some examples


[[example]]
name              = "blink"
required-features = ["dev", "rt"]

[[example]]
name              = "uarte"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_delayed_tx"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_id"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_only_rx"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_only_tx"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_reg_modify"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_reg_rw"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_reg_short"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_rx_tx"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_subreg"
required-features = ["dev", "rt"]

[[example]]
name              = "dw1000_subreg_ext_addr"
required-features = ["dev", "rt"]


[profile.release]
codegen-units = 1
lto           = true
opt-level     = 3
